<a href="https://colab.research.google.com/github/kanishqdhangar/machine-learning/blob/main/numpy/np-array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1= np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2=np.zeros((1,2))
arr2

array([[0., 0.]])

In [ ]:
arr3=np.ones((3,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr4=np.empty((2,2))
arr4

array([[3.47402850e-315, 0.00000000e+000],
       [6.64725559e-310, 5.78883674e-317]])

In [ ]:
arr5=np.arange(1,14,2)
arr5

array([ 1,  3,  5,  7,  9, 11, 13])

In [ ]:
arr6=np.linspace(10,20,10)
arr6

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
arr1.shape


(5,)

In [ ]:
arr2.shape

(1, 2)

In [ ]:
arr1.ndim

1

In [ ]:
arr2.ndim

2

In [ ]:
arr7=np.arange(24).reshape(6,4)
arr7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr7[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [ ]:
arr7[4:,2:4]

array([[18, 19],
       [22, 23]])

In [ ]:
for i in np.nditer(arr7):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [ ]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [ ]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [ ]:
arr2>3

array([ True,  True,  True,  True,  True,  True])

In [ ]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [ ]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [ ]:
arr4.max()

np.int64(11)

In [ ]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [ ]:
arr=np.random.randint(low=10, high=100, size=20).reshape(4,5)
arr

array([[81, 91, 93, 80, 51],
       [55, 47, 58, 44, 43],
       [83, 97, 70, 66, 74],
       [47, 97, 49, 57, 72]])

In [ ]:
arr>50

array([[ True, False, False, False, False],
       [False,  True, False,  True,  True],
       [ True,  True,  True,  True, False],
       [False,  True, False,  True, False]])

In [ ]:
arr[arr>50]

array([92, 73, 92, 90, 74, 73, 81, 96, 85, 87])

In [ ]:
arr[(arr>50) & (arr%2!=0)]

array([81, 91, 93, 51, 55, 83, 97, 97, 57])