<a href="https://colab.research.google.com/github/kanishqdhangar/machine-learning/blob/main/numpy/np-array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1= np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr2=np.zeros((1,2))
arr2

array([[0., 0.]])

In [4]:
arr3=np.ones((3,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
arr4=np.empty((2,2))
arr4

array([[3.47402850e-315, 0.00000000e+000],
       [6.64725559e-310, 5.78883674e-317]])

In [6]:
arr5=np.arange(1,14,2)
arr5

array([ 1,  3,  5,  7,  9, 11, 13])

In [7]:
arr6=np.linspace(10,20,10)
arr6

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])